mybatis-plus:
  type-aliases-package: cn.youfull.trimhelp.entity
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    suffix:  .html
    mode: LEGACYHTML5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.174.82:3306/decoratestate?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 20
      auto-commit: true
      pool-name: MyhikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 39.105.162.7
    port: 6379
    password: youzhilong6
    lettuce:
      pool:
        max-active: 10
        min-idle: 1
        max-idle: 8 #最大空闲连接数
        max-wait: -1
      shutdown-timeout: 1000
    database: 1


pageSize: 5
endpoint: oss-cn-beijing.aliyuncs.com
keyid: LTAI4FoKr9XUMcABqMidR6Ep
keysecret: 6sURs6Y5S9PsUyuODu8iosVoDSxreG
bucketname1: th-images1
filehost: img/